# Generated by Django 5.1.3 on 2025-10-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msapps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_size',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='product-images/'),
        ),
        migrations.DeleteModel(
            name='ProductStock',
        ),
    ]
