# Generated by Django 5.1.3 on 2025-10-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msapps', '0002_remove_product_product_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(default=0, max_length=500, verbose_name='Contact Number'),
            preserve_default=False,
        ),
    ]
